### ISSUE TITLE
Build issue on MacOS 14.4.1

### ISSUE THREAD

**Issue by jsdonato** [bitwuzla/bitwuzla#153]
Hello Bitwuzla team,

I am having an issue building Bitwuzla with the `--cryptominisat` configure flag invoked.  More specifically, when I configure with the prefix set to a directory named `build` in the top level directory of the Bitwuzla project and I invoke the `--kissat` and `--cryptominisat` options when configuring I then get the following build errors after running `cd build && ninja install`.

```
In file included from ../src/sat/cryptominisat.cpp:15:
../src/sat/cryptominisat.h:18:10: fatal error: 'cryptominisat5/cryptominisat.h' file not found
#include <cryptominisat5/cryptominisat.h>

In file included from ../src/sat/sat_solver_factory.cpp:14:
../src/sat/cryptominisat.h:18:10: fatal error: 'cryptominisat5/cryptominisat.h' file not found
#include <cryptominisat5/cryptominisat.h>
```

I was able to fix this by changing the include path for cryptominisat in the `src/sat/cryptominisat.h` file.  Is this an issue your team is experiencing too?

Thanks!

**Comment by aniemetz** [comment]
This is now fixed on main, let us know if you still run into issues.

**Comment by jsdonato** [comment]
@aniemetz Hello, I apologize for the late follow up.  I pulled from main and I am still getting the same issue unfortunately.  I am getting the following build error
```
../src/sat/cryptominisat.h:18:10: fatal error: 'cryptominisat5/cryptominisat.h' file not found
#include <cryptominisat5/cryptominisat.h>
``` 

It appears that the cryptominisat source header is still in the following directory.
```
>>$ find . -name 'cryptominisat\.h'
./subprojects/cryptominisat-5.11.21/src/cryptominisat.h
```

The changes I made in PR #155 still fixes it on my machine.  I am not sure if this is the case on all platforms though.  Thanks again!!

**Comment by jsdonato** [comment]
@aniemetz Hello again.  I tried re cloning the repo rather than pulling from main and everything works!  I apologize for the mix up.

**Comment by aniemetz** [comment]
@jsdonato glad that it works!
